project:
  type: website
  output-dir: docs

website:
  title: "MG ML"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/mgallimore88
      - icon: envelope
        href: mailto:mgallimore88@gmail.com
      - icon: linkedin
        href: https://www.linkedin.com/in/michael-gallimore-4104536a/
format:
  html:
    theme: lux
    # themes: https://bootswatch.com/
    css: styles.css



